version: "3.7"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: miniflux2
    ports:
      - 5432:5432